### ISSUE TITLE
ansible: use `proxy_env` variable for MEV only

### ISSUE THREAD

**Issue by glimchb** [opiproject/lab#8]
default({}) : what am I doing wrong ?
```
[mev:vars]
proxy_env="{'http_proxy': 'http://192.168.0.1:3128', 'https_proxy': 'http://192.168.0.1:3128'}"
```
in the inventory, and then use it like this in playbook
```
- name: 
 hosts: all
 become: yes
 environment: "{{ proxy_env | default({}) }}"
 tasks:
   - ansible.builtin.package: state=present name=python3-pip,sshpass,git
```
throws error...
